In [1]:
import numpy as np

In [15]:
def make_neighbour_indices(n):
    return np.dstack((np.arange(n)[:-1], np.arange(n)[1:])).reshape((-1, 2))

def H(spins, pair_indices, couplings=None, magnetic_fields=None):
    n = len(spins)

    if couplings is None:
        couplings = np.zeros((n, n))
        couplings[pair_indices[:,0], pair_indices[:,1]] = np.ones(len(pair_indices))
        
    print(couplings)
    
    if magnetic_fields is None:
        magnetic_fields = np.zeros(n)
        
    return - spins.T @ couplings @ spins - magnetic_fields @ spins

In [16]:
spins = np.array([[1], [-1], [1], [1], [-1]])
n = len(spins)
H(spins, make_neighbour_indices(n))

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


array([[2.]])